name: .NET Core

environment:
  access_token:
    secure: efdb6c1dff2024e6c7f4386fdd7a3b7d7ea48a63

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Git configure
      run: git config --global credential.helper
        && ps: Add-Content -Path "$HOME\.git-credentials" -Value "https://$($env:access_token):x-oauth-basic@github.com`n" -NoNewline
        && git config --global user.email "www20040718@163.com"
        && git config --global user.name "DreamEnderKing"
    - name: Try dotnet service
      run: dotnet new console -n console1 -o console1
        && cd console1
        && git init
        && git remote add origin https://github.com/DreamEnderKing/PipeCon1.git
        && git add -A && git commit -m "Update"
        && git push --set-upstream origin master
    - name: Prepare for next step
      run: cd ../
    - name: Install dependencies
      run: dotnet restore FCsharp
    - name: Build
      run: dotnet build FCsharp --configuration Release --no-restore
    - name: Test
      run: cd FCsharp && dotnet run FCsharp
