name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Try dotnet service
      run: dotnet new console console1 -o console1
    - name: Install dependencies
      run: dotnet restore FCsharp
    - name: Build
      run: dotnet build FCsharp --configuration Release --no-restore
    - name: Test
      run: dotnet test FCsharp --no-restore --verbosity normal
    - name: Post
      run: github push
